### ISSUE TITLE
error

### ISSUE THREAD

**Issue by milanifard** [milanifard/WebDocFetcher#2]
I got following error after I tried to add new site for crawl:

(
    [0] => HY000
    [1] => 1364
    [2] => Field 'doc_formats' doesn't have a default value
)
Array
(
    [0] => سایت دانشگاه فردوسی
    [1] => www.um.ac.ir
    [2] => 1
    [3] => 4
    [4] => 100
    [5] => 2
)
Array
(
    [0] => Array
        (
            [file] => D:\wamp64\www\sadaf\www\shares\pdodb.class.php
            [line] => 139
            [function] => backtrace
            [class] => pdodb
            [object] => pdodb Object
                (
                    [driver:pdodb:private] => mysql
                    [host:pdodb:private] => 
                    [default_db] => sadaf
                    [user:pdodb:private] => 
                    [pass:pdodb:private] => 
                    [dsn:pdodb:private] => mysql:dbname=sadaf;host=localhost
                    [pdo:pdodb:private] => PDO Object
                        (
                        )

                    [statement:pdodb:private] => PDOStatement Object
                        (
                            [queryString] => insert into SystemDBLog (page,query,SerializedParam,UserID,IPAddress,SysCode,ExecuteTime,QueryStatus,DBName)
            values (:page,:query,:SerializedParam,:UserID,:IPAddress,:SysCode,:ExecuteTime,:QueryStatus,:DBName)
                        )

                    [AffectedRows:pdodb:private] => 1
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [1] => Array
        (
            [file] => D:\wamp64\www\WebDocFetcher\www\sadaf\crawl.php
            [line] => 19
            [function] => ExecuteStatement
            [class] => pdodb
            [object] => pdodb Object
                (
                    [driver:pdodb:private] => mysql
                    [host:pdodb:private] => 
                    [default_db] => sadaf
                    [user:pdodb:private] => 
                    [pass:pdodb:private] => 
                    [dsn:pdodb:private] => mysql:dbname=sadaf;host=localhost
                    [pdo:pdodb:private] => PDO Object
                        (
                        )

                    [statement:pdodb:private] => PDOStatement Object
                        (
                            [queryString] => insert into SystemDBLog (page,query,SerializedParam,UserID,IPAddress,SysCode,ExecuteTime,QueryStatus,DBName)
            values (:page,:query,:SerializedParam,:UserID,:IPAddress,:SysCode,:ExecuteTime,:QueryStatus,:DBName)
                        )

                    [AffectedRows:pdodb:private] => 1
                )

            [type] => ->
            [args] => Array
                (
                    [0] => Array
                        (
                            [0] => سایت دانشگاه فردوسی
                            [1] => www.um.ac.ir
                            [2] => 1
                            [3] => 4
                            [4] => 100
                            [5] => 2
                        )

                )

        )

)

**Comment by milanifard** [comment]
I altered the site table with following command for temporary by passing this error:
ALTER TABLE `sadaf`.`sites` 
CHANGE COLUMN `doc_formats` `doc_formats` VARCHAR(3000) NOT NULL DEFAULT ' ' ;

**Comment by NajmeHabibi** [comment]
bug fixed. check it again please @milanifard
