### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by milanifard** [milanifard/WebDocFetcher#3]
I tried to crawl this site: um.ac.ir and also this site: khev.um.ac.ir. It did not work. I trace the execution path and I found out that after calling $response = curl_exec($handle); in DocCrawler.php, $response was empty.
Is there any configuration that u forgot to mention in installation file or anything else cause this problem?

**Comment by NajmeHabibi** [comment]
Thanks for your feedback @milanifard.
Yes, it might be necessary to do some configuration first.
We added detailed instructions in README.md on how to run the project.
Please pull the project again and follow the instructions.
For instance, here is the crawling result of um.ac.ir website:
![photo_2021-02-06_18-16-35](https://user-images.githubusercontent.com/42568062/107126392-e2a0cd80-68c4-11eb-8485-49754f393fce.jpg)
